name: "Submodule Checkout"
author: "James Webb"
description: "GitHub action for checking out submodules defined within a repository"
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'box'
  color: 'blue'